name: CI

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE
  push:
    paths-ignore:
      - "**.md"
      - LICENSE
  schedule:
    # At 12:00 on Monday
    - cron: 0 12 * * 1

jobs:
  plugin_test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Test plugin
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: helm diff version

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run ShellCheck
        run: shellcheck bin/*
